language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"
  yarn: true

script:
  - yarn docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: .vuepress/dist
  on:
    branch: master
